version: '3.3'
services:
  db_test:
    image: mariadb:latest
    ports:
      - 3307:3306
    volumes:
      - /Users/hendrikaraujo/Projects/graphql-node-api/docker/data_test:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=anitnelav
      - MYSQL_DATABASE=app_test
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - /Users/hendrikaraujo/Projects/graphql-node-api/docker/data_dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=anitnelav
      - MYSQL_DATABASE=app_development
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  app_graphql:
    image: adminer:latest
    links:
      - db
      - db_test
    ports:
      - 8080:8080